# .streamlit/config.toml

[server]
runOnSave       = false
headless        = true
port            = 8501
enableCORS      = false
maxUploadSize   = 200

[logger]
level = "error"      # only show errors, hide info/warnings

[theme]
primaryColor             = "#1f77b4"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
font                     = "sans serif"
