# .streamlit/config.toml

[server]
runOnSave       = false      # disable live‐reload on save
headless        = true       # run without opening a browser
port            = 8501
enableCORS      = false
maxUploadSize   = 200        # in MB

[watcher]
type = "none"                # disable the module‐path watcher completely

[theme]
primaryColor             = "#1f77b4"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
font                     = "sans serif"
