# .streamlit/config.toml

[server]
# Disable Streamlit’s file‐watcher so it won’t inspect torch internals
runOnSave = false

# Run headless on port 8501 and disable CORS
headless = true
port = 8501
enableCORS = false

# Allow larger uploads if you need it (in MB)
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
font = "sans serif"
